### ISSUE TITLE
API Domain change

### ISSUE THREAD

**Issue by geromegrignon** [brucou/realworld-kingly-svelte#2]
Hello!

Due to governance changes, we are now using the `realworld.io` domain for the RealWorld demo (both client and API).
Requests from `conduit.productionready.io` are redirected to `api.realworld.io`, but such a redirection might lead to inconsistent responses.

We encourage domain change for the community.
If this repository is maintained anymore, we'll consider hosting a demo of your implementation in a few weeks with the domain change.

The demo link will be added to the RealWorld documentation.

**Comment by brucou** [comment]
Hi Jerome,

yes this is still maintained and I'll be glad if you host it on the new domain. Is there any changes for me to do on my side? You said the requests are redirected so I assume things will continue to work fine except for what you described as inconsistent responses.

**Comment by brucou** [comment]
By the way, what are the changes in realworld? team? governance? roadmap?

**Comment by geromegrignon** [comment]
hey @brucou, I created a PR #3 to make related changes.

Once changed and your demo (https://rw-kingly-svelte-bricoi1.vercel.app/) deployed, you should see no changes.


About changes, There are pinned issues [here](https://github.com/gothinkster/realworld/issues) to explain them.
Feel free to contact me if you need further explanations.
